#!/usr/bin/env bash

play -q ~/nix/sounds/brb.mp3&
figlet "WE'LL" | lolcat
sleep .75s
figlet "        BE" | lolcat
sleep .75s
figlet "                RIGHT" | lolcat
sleep .5s
figlet "                            BACK" | lolcat
