#!/usr/bin/env bash

play -q ~/nix/sounds/brb.mp3&
figlet "WE'LL" | clolcat
sleep .75
figlet "        BE" | clolcat
sleep .75
figlet "                RIGHT" | clolcat
sleep .5
figlet "                            BACK" | clolcat
