#!/usr/bin/env bash
while true; do
  platform="${uname}"
   A=$((900 + RANDOM % 900))
   play ~/nix/sounds/alert.mp3 &
   if [[ $platform = "Linux" ]];then
    dunstify -u critical -t 5000 "Hey, Hydrate you retard!"
  else
    osascript -e 'display notification "Drink you Retard!" with title "hydro"'
  fi
  sleep $A
done
