#!/usr/bin/env bash

if [[ $(pgrep hydro.sh) ]];then
  echo "hydro.sh found, closing"
  pkill hydro
  dunstify -t 2000 "Hydro is off"
else
  echo "Starting hydro.sh"
  dunstify -t 2000 "Hydro is on"
  hydro &
  exit
fi
